import type { Metadata } from "next";
import { Roboto, Inter } from "next/font/google";
import { ThemeProvider } from "@/providers/ThemeProvider";
import "./globals.css";
import { Header } from "@/components/common/Header";
import { Separator } from "@/components/ui/separator";
import { Navigation } from "@/components/common/Navigation";
import { Footer } from "@/components/common/Footer";
import { Toaster } from "@/components/ui/toaster";

// const roboto = Roboto({
//   weight: ["100", "300", "400", "500", "700", "900"],
//   subsets: ["latin"],
//   style: ["italic", "normal"],
//   display: "swap",
//   variable: "--font-roboto",
// });

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className={`${inter.className} bg-application text-zinc-200`}>
        <ThemeProvider attribute="class" defaultTheme="light" disableTransitionOnChange>
          <main className="min-h-screen p-8">
            <div className="mx-auto flex max-w-3xl flex-col gap-6 rounded-lg bg-zinc-800/40 p-6 shadow-md shadow-black backdrop-blur-sm">
              <Header />

              <Separator className="my-2 bg-zinc-400" />

              <Navigation />

              {children}

              <Separator className="my-2 bg-zinc-400 " />

              <Footer />
            </div>
          </main>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
